# Generated by Django 5.2.11 on 2026-04-11 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def merge_beers_and_ratings_that_match(apps, schema_editor):
        Beer = apps.get_model("api", "Beer")
        Rating = apps.get_model("api", "Rating")
        RatingSeen = apps.get_model("api", "RatingSeen")

        for beer in Beer.objects.all():
            matching_beers = Beer.objects.filter(
                brewery=beer.brewery,
                name=beer.name,
                type=beer.type,
            )
            if matching_beers.count() > 1:
                primary_beer = matching_beers.first()
                duplicate_beers = matching_beers.exclude(id=primary_beer.id)

                for duplicate in duplicate_beers:
                    Rating.objects.filter(beer=duplicate).update(beer=primary_beer)
                    RatingSeen.objects.filter(rating__beer=duplicate).delete()  # Remove seen status for ratings that are being merged
                    duplicate.delete()

    operations = [
        migrations.AddField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RatingSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_by', to='api.rating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'rating')},
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),

        migrations.RunPython(
            code=merge_beers_and_ratings_that_match,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
